### ISSUE TITLE
practical guidelines

### ISSUE THREAD

**Issue by musicformellons** [naiquevin/tapestry#1]
Thanks for this nice library! What i would like to have is some guidelines on:
- how would the typical REST CRUD look using tapestry?
- would you recommend putting 'everything' (also non-dynamic queries) in this structure?

**Comment by naiquevin** [comment]
Hello. Thanks for the kind words. 

> how would the typical REST CRUD look using tapestry?

I'd say, it depends on whether or not the queries are complex enough that pgTAP tests seem necessary for them. 

In my experience, usually select queries are more likely to contain business logic and/or dynamic conditional clauses, whereas `insert/update/delete` queries are much simpler in comparison. If the query is too simple e.g. 
```
   DELETE from table where id = $1
``` 

then creating templates and pgTAP tests for it seems pointless. The only the kind of non-select queries I can think of where pgTAP tests can help is for UPSERT (`INSERT INTO .. ON CONFLICT .. DO UPDATE` kind of statements). 

> would you recommend putting 'everything' (also non-dynamic queries) in this structure?

In my personal projects, I have used tapestry for non-dynamic queries but not for all of them. If you have a non-dynamic query which has considerable business logic inside it, then it's recommended to write pgTAP tests and so tapestry could be useful in that case. 

To answer your question more generally - you can think of tapestry as a tool that mainly solves 2 problems: 
1. makes it easy to maintain dynamic queries 
2. provides the guarantee that pgTAP tests run the exact same query as what the application runs

So if your queries are so simple that neither of the above 2 points benefit, then tapestry is not of much use.

**Comment by musicformellons** [comment]
Great, thanks! I'm really liking it so far. I was first happy user of [cornucopia](https://cornucopia-rs.netlify.app/), but it does not (yet) support e.g. postgis types. I know sqlx and diesel do, but prefer more raw approach but did not really know how to set it up. Now I do, thanks!
