### ISSUE TITLE
pg_prove installation

### ISSUE THREAD

**Issue by musicformellons** [naiquevin/tapestry#2]
I'm using a postgres container image. AFAICT pg_prove needs to be installed on that container then right? So not on the host (vs pg_format which needs to be installed on the host/ render environment).

**Comment by naiquevin** [comment]
Yes, you are right. `pg_prove` needs to be installed on the container and `pg_format` needs to be available in your dev env. I am currently working on adding support for other sql formatters too on a separate branch. Let me know if you use anything other than `pg_format`, I'd be happy to add support for it. 

Also, in case you missed it in the docs, this repo provides a docker based workflow for running pgTAP tests - https://naiquevin.github.io/tapestry/user-guide/docker/. It's generic enough that you can build the container once and use it for running any pgTAP tests against any schema (not tightly coupled with tapestry as such).
